### ISSUE TITLE
queue.Empty exception crash

### ISSUE THREAD

**Issue by yubrshen** [kantord/SeaGOAT#241] opened 2023-09-22 18:36 UTC
When performing 
`yshen@L-2JDM8S2:~/dev/icsr-study/projects/icsr-root$ seagoat-server start .
2023-09-22 11:25:47,414 Creating server...
2023-09-22 11:25:47,416 Starting worker thread...
2023-09-22 11:25:47,430 Serving on http://0.0.0.0:34373
2023-09-22 11:25:49,086 Checking repository for new changes`
got the following:
`2023-09-22 11:25:47,430 Serving on http://0.0.0.0:34373
2023-09-22 11:25:49,086 Checking repository for new changes
Exception in thread Thread-1 (_worker_function):
Traceback (most recent call last):
  File "/home/yshen/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 76, in _worker_function
    task = self._task_queue.get(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshen/miniconda3/envs/seagoat-python311/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yshen/miniconda3/envs/seagoat-python311/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/yshen/miniconda3/envs/seagoat-python311/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yshen/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 81, in _worker_function
    self.handle_maintenance(context)
  File "/home/yshen/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/task_queue.py", line 50, in handle_maintenance
    remaining_chunks_to_analyze = context["seagoat_engine"].analyze_codebase(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshen/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 84, in analyze_codebase
    return self._create_vector_embeddings(minimum_chunks_to_analyze)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshen/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 106, in _create_vector_embeddings
    for chunk in file.get_chunks():
                 ^^^^^^^^^^^^^^^^^
  File "/home/yshen/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/file.py", line 79, in get_chunks
    lines = self._get_file_lines()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshen/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/file.py", line 34, in _get_file_lines
    for i, line in enumerate(source_code_file.read().splitlines())
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`

Running in a Ubuntu 24.4 on WSL2/Windows 11. The current directory in which running seagoat-server is a git repo of Java, with all files checked-in.
It might or might not be relevant:
When the exception happened, I was doing `kill -9 %4` to a seagoat server running on a different path, which had exception of KeyError.

**Comment by kantord** [comment] 2023-09-22 21:16
I think that probably the main thing here is this:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`

at least that suggests to me that it is a duplicate of this https://github.com/kantord/SeaGOAT/issues/227

If that is not accurate, please feel free to reopen

**Closed by kantord** 2023-09-22 21:16 UTC
