### ISSUE TITLE
Document the location of the database

### ISSUE THREAD

**Issue by snej** [kantord/SeaGOAT#246] opened 2023-09-23 17:35 UTC
I can’t find anything in the README that says where the server stores its data. And I’ve looked in the repo dir, my home dir and the SeaGoat installation dir (`~/.local/pipx…`) and found nothing that looks like it, even invisible files.

Since I imagine the database gets pretty big, users should know how to remove it if they uninstall SeaGoat or need to free up storage (or have a damaged install as I seem to have.)

It would also be nice if the server had a subcommand to delete an index for a repo.

**Comment by kantord** [comment] 2023-09-24 15:17
> Since I imagine the database gets pretty big, users should know how to remove it if they uninstall SeaGoat or need to free up storage (or have a damaged install as I seem to have.)

This part is a duplicate of this issue:

https://github.com/kantord/SeaGOAT/issues/14

**Comment by kantord** [comment] 2023-09-24 15:19
>  can’t find anything in the README that says where the server stores its data. And I’ve looked in the repo dir, my home dir and the SeaGoat installation dir (~/.local/pipx…) and found nothing that looks like it, even invisible files.

regarding this one, I am thinking about adding this to a command so that it's easy to figure it out, becase it is operating system dependent. And I will add documentation about it

**Closed** 2023-09-24 16:55 UTC

**Comment by kantord** [comment] 2023-09-24 16:57
closed because now it's possible to easily find out where these files are located and it's documented in README.md as well as on the documentation website. For posterity, the TLDR is `seagoat-server server-info` and the full documentation is: https://kantord.github.io/SeaGOAT/latest/server/#retrieving-server-information

**Comment by snej** [comment] 2023-09-24 17:35
Thanks! I upgraded, found the cache location and deleted it so I can start from scratch.

(I hadn’t thought of looking in `~/Library/Caches` because the docs said Seagoat wasn’t supported on macOS yet … thanks for being Mac-friendly!)
