### ISSUE TITLE
remote seagoat-server and local gt client path mismatch causes FileNotFoundError

### ISSUE THREAD

**Issue by cori** [kantord/SeaGOAT#270] opened 2023-09-28 15:28 UTC
I'm trying to run `seagoat-server` on a remote host - i've got it running and exposed and have my client configured correctly and when i run the server not in the background I can see my query hit the server, but my query ends up with a `FileNotFoundError` referencing a path that most definitely exists on the remote repo and a file that exists in the local repo at a different path - the two repos are structurally the same of course but at different parent paths.

If I `ln -s` the repo to the same parent on the server side and then run the server from the symlink path, I don't receive an error.

Not sure if this is expected and if so whether this workaround should be documented somewhere, or if respecting a repo root would be more effective.

_Originally posted by @cori in https://github.com/kantord/SeaGOAT/discussions/269_

**Comment by kantord** [comment] 2023-09-28 15:58
I am suspecting that this is because the CLI is taking the full path from the server as it is instead of building a new path. I will  make a test case in order to prove this and ship the fix if possible

**Comment by kantord** [comment] 2023-09-28 16:12
hmm, maybe my theory is not correct. I wrote this test case which I thought should reproduce your problem:

```python


@pytest.mark.usefixtures("mock_accuracy_warning")
def test_connecting_to_remote_server(snapshot, repo, mocker, runner, temporary_cd, server, create_config_file):
    create_config_file({"client": {"host": server}})
    mocker.patch("os.isatty", return_value=True)
    query = "JavaScript"
    
    with tempfile.TemporaryDirectory() as tmpdirname:
        shutil.copytree(repo.working_dir, os.path.join(tmpdirname, 'repo_copy'), dirs_exist_ok=True)
        with temporary_cd(os.path.join(tmpdirname, 'repo_copy')):
            result = runner.invoke(seagoat, [query, ".", "--no-color"])

    assert str(result.output) == snapshot
    assert result.exit_code == 0
```

But apparently, this test case does not fail. Actually it returns results as expected :thinking:

**Comment by kantord** [comment] 2023-09-28 16:18
> referencing a path that most definitely exists on the remote repo and a file that exists in the local repo at a different path - the two repos are structurally the same of course but at different parent paths.

ok, I wasn't really paying attention to this part. Ok, that is an edge case I didn't think of and it seems like it's not trivial how to deal with it:

- We could ignore those files as the use doesn't have them locally anyways. This will be probably what I will end up implementing, but I don't love this solution
- Send all files from the remote server if they are in a result. I don't like this approach because it's very wasteful and would probably slow things down
- Add and endpoint to allow the client to download these files on the fly. I don't think it's viable because it would be a performance problem and it would make it easier to steal data using the SeaGOAT server if someone gets unauthorized access

**Comment by kantord** [comment] 2023-09-28 16:19
Maybe the best way is to ignore these files, but show a warning to the user that the remote server has a file that they don't have

**Comment by kantord** [comment] 2023-09-28 17:29
ok I think this test can reproduce the problem


```py

@pytest.mark.usefixtures("mock_accuracy_warning", "bat_available")
def test_connecting_to_remote_server(snapshot, repo, mocker, runner, temporary_cd, server, create_config_file, bat_calls):
    create_config_file({"client": {"host": server}})
    mocker.patch("os.isatty", return_value=True)
    query = "JavaScript"
    
    def query_server_side_effect(*args, **kwargs):
        results = query_server(*args, **kwargs)
        
        results =  [{**result, "fullPath": "/non/existent/path/" } for result in results]
        for result in results:
            print("🍌", result)

        return results
    
    mocker.patch("seagoat.cli.query_server", side_effect=query_server_side_effect)
    
    with tempfile.TemporaryDirectory() as tmpdirname:
        shutil.copytree(repo.working_dir, os.path.join(tmpdirname, 'repo_copy'), dirs_exist_ok=True)
        repo.add_file_change_commit(
            file_name="example_should_not_exist_in_copy.txt",
            contents="""JavaScript is an amazing programming language""",
            author=repo.actors["John Doe"],
            commit_message="Add fruits data",
        )
        with temporary_cd(os.path.join(tmpdirname, 'repo_copy')):
            result = runner.invoke(seagoat, [query, ".", "--no-color"])

    assert result.exit_code == 0
    assert bat_calls == snapshot
    assert len(bat_calls) == 3
```

**Comment by kantord** [comment] 2023-09-28 19:30
should be fixed after the latest update! (should be released to pip within a couple minutes)

**Closed** 2023-09-28 19:29 UTC
