### ISSUE TITLE
"UnicodeDecodeError: 'charmap' codec can't decode byte 0x81"

### ISSUE THREAD

**Issue by snej** [kantord/SeaGOAT#250] opened 2023-09-24 17:56 UTC
Me again :) I erased the server cache, upgraded with pipx to 0.31.0, rebuilt the index and tried another query. This time I got a different exception.

Looks like a source file is in an unexpected text encoding and has bytes that fail to decode using cp1254, which [Wikipedia tells me](https://en.wikipedia.org/wiki/Windows-1254) is a Windows text encoding primarily used for Turkish(!)

The filename doesn’t appear in the backtrace or server logs, and at first I couldn’t figure out why there might be Turkish in the repo, but then I remembered the repo has [a submodule](https://github.com/snej/sqlite3-unicodesn/) that handles language-aware word stemming for full-text search. [One of the files handles Turkish](https://github.com/snej/sqlite3-unicodesn/blob/master/libstemmer_c/src_c/stem_UTF_8_turkish.c), although I didn’t spot any non-ASCII characters in it.

Anyway, back in the dark days before everything was UTF-8, I remember that to parse arbitrary files without errors the heuristic was to (a) attempt to parse as UTF-8, (b) if that fails, parse as CP-1252 aka ISO-8859-1. The latter will never fail since it maps every byte value to a character, and it’s a superset of ASCII and the most common non-UTF-8 text format.

```
Exception in thread Thread-1 (_worker_function):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 79, in _worker_function
    self._handle_task(context, task)
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 66, in _handle_task
    result = handler(context, *task.args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/task_queue.py", line 78, in handle_query
    context["seagoat_engine"].fetch_sync(
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 163, in fetch_sync
    loop.run_until_complete(self.fetch(*args, **kwargs))
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 269, in __step
    result = coro.throw(exc)
             ^^^^^^^^^^^^^^^
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 149, in fetch
    results = await asyncio.gather(*async_tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/sources/ripgrep.py", line 45, in fetch
    return _fetch(query_text, str(path), limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/sources/ripgrep.py", line 33, in _fetch
    files[relative_path] = Result(str(relative_path), absolute_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/result.py", line 77, in __init__
    self.line_texts = self._read_lines()
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/result.py", line 87, in _read_lines
    return source_code_file.read().splitlines()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 37401: character maps to <undefined>
```

**Comment by kantord** [comment] 2023-09-24 20:18
> Looks like a source file is in an unexpected text encoding and has bytes that fail to decode using cp1254, which [Wikipedia tells me](https://en.wikipedia.org/wiki/Windows-1254) is a Windows text encoding primarily used for Turkish(!)

Can you verify that the file is **not** in that encoding? And by the way, if the content of that file is not private, could you share it? maybe I could try to convert it into a test case to make sure this bug does not arise again after it is fixed

**Comment by snej** [comment] 2023-09-24 21:12
I don’t know for sure which file it is; I was just guessing on the basis of CP-1254 being used for Turkish, and one known file with “turkish” in the name. 

If you could add the filename to the exception log somehow, I could show you which file. But of course, it’d be best if the code gracefully handled any encoding, even broken ones.

**Comment by snej** [comment] 2023-09-24 21:26
This is the repo: https://github.com/couchbase/couchbase-lite-C

**Comment by cori** [comment] 2023-09-24 23:21
I am running into the same error on a private repo (ofc with different `byte` and `position` values `UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2129: character maps to <undefined>`). Happy to dig into logs and whatnot a bit later - haven't even dug up where those are yet.

**Comment by cori** [comment] 2023-09-25 10:14
Oh it looks like maybe #240 combined with #231 might address this? I ran into this both when trying to run from source and when running from the `pipx` version yesterday, so I _think_ #240 was insufficient to resolve completely.

**Comment by kantord** [comment] 2023-09-25 12:08
> Oh it looks like maybe #240 combined with #231 might address this? I ran into this both when trying to run from source and when running from the `pipx` version yesterday, so I _think_ #240 was insufficient to resolve completely.

I wonder if #240 actually caused this problem

**Comment by kantord** [comment] 2023-09-25 12:08
The 2 of you are running into the same problem, I think it must be something common then

**Comment by kantord** [comment] 2023-09-25 12:26
> This is the repo: https://github.com/couchbase/couchbase-lite-C

I have quickly "fake analyzed" this repo (meaning I did not actually create the vector embeddings) but it seems that at least it's able to read all files, at least on linux :thinking:  but it seems that actually this problem happened for you when showing the results, which is again, weird. I mean, if it fails when showing the results, then it should have failed in the beginning when the files were analyzed :thinking:

**Comment by cori** [comment] 2023-09-25 12:35
I apologize - I didn't read carefully enough an am not familiar enough with the project to note - I am running into the same base exception but through a different stacktrace - mine is in the analyze phase

```
Exception in thread Thread-1 (_worker_function):
Traceback (most recent call last):
  File "/home/cori/code/SeaGOAT/seagoat/queue/base_queue.py", line 76, in _worker_function
    task = self._task_queue.get(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cori/code/SeaGOAT/seagoat/queue/base_queue.py", line 81, in _worker_function
    self.handle_maintenance(context)
  File "/home/cori/code/SeaGOAT/seagoat/queue/task_queue.py", line 50, in handle_maintenance
    remaining_chunks_to_analyze = context["seagoat_engine"].analyze_codebase(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cori/code/SeaGOAT/seagoat/engine.py", line 84, in analyze_codebase
    return self._create_vector_embeddings(minimum_chunks_to_analyze)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cori/code/SeaGOAT/seagoat/engine.py", line 106, in _create_vector_embeddings
    for chunk in file.get_chunks():
                 ^^^^^^^^^^^^^^^^^
  File "/home/cori/code/SeaGOAT/seagoat/file.py", line 81, in get_chunks
    lines = self._get_file_lines()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cori/code/SeaGOAT/seagoat/file.py", line 36, in _get_file_lines
    for i, line in enumerate(source_code_file.read().splitlines())
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/encodings/cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2129: character maps to <undefined>
```

I can split this into a different issue.

**Comment by kantord** [comment] 2023-09-25 13:05
but in the end it's the same encoding which is suspicious :thinking:

**Comment by kantord** [comment] 2023-09-25 14:35
using a script that randomly generates byte sequences that are valid utf-8, I managed to find some examples that cause the same error:

```bash
b'\xc3\x8f>WP\x1b'
b'\x1emh\xdf\x90F'
b'\xe8\xb2\x81;N0uA'
 b'\x19|\x14G?<\x0c\\\x17\xeb\xbd\x8f>|'
```

These are valid utf-8 but chardet does not detect them as such. And these examples also examples where an exception is raised when trying to read them as the encoding that chardet detected them as. I think this should be the reason, let me write some test cases to reproduce it

**Comment by kantord** [comment] 2023-09-25 15:50
should be fixed now, feel free to reopen if you face this error again, or anything similar

**Closed** 2023-09-25 15:49 UTC

**Comment by cori** [comment] 2023-09-27 13:48
some combination of these fixes also resolved my possibly-tangential issue; thanks!

**Comment by ChrisB85** [comment] 2023-10-30 21:20
I've just encountered a similar problem, here's the full stacktrace [https://pastebin.com/rBCh91Ld](https://pastebin.com/rBCh91Ld)

**Comment by kantord** [comment] 2023-11-01 18:49
> I've just encountered a similar problem, here's the full stacktrace https://pastebin.com/rBCh91Ld

hi @ChrisB85 !

Thank you for posting the stack trace. Unfortunately based on the stacktrace I am not sure what the exact issue is.

Could you please:

- Share the repo itself if it is open source
- If that is not possible, try to make a new repo with a minimal reproduction

It could also be useful if you could describe what operating system you use and what character encoding your files use
